name: New Provider Request
description: Request a new provider to be added to CinePro
title: "Provider Request: "
labels: [ "🌟enhancement", "📀provider", "🔺needs-triage" ]

body:
  - type: markdown
    attributes:
      value: |
        Hey There! 👋 Thanks for suggesting a new provider for CinePro! 🚀
        Before submitting your request, please ensure the provider is not already supported.

        Please fill out this template to help us understand your request better.

        > [!NOTE]
        > Before submitting, please check if your provider request is already suggested in the [existing issues](https://github.com/cinepro-org/backend/issues).

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        **Please check these before submitting:**
      options:
        - label: I have checked the existing issues and this is not a duplicate
          required: true
        - label: I have read the [README.md](https://github.com/cinepro-org/backend/blob/main/README.md) and ensured that this provider is not already supported
          required: true
        - label: I have included all relevant details in this request
          required: true
        - label: I did not answer truthfully to **ALL** the above checkboxes
          required: false

  - type: input
    attributes:
      label: Provider Name
      description: What is the name of the provider you want to add?
      placeholder: |
        ExampleProvider
    validations:
      required: true

  - type: input
    attributes:
      label: Provider URL
      description: What is the main website or API endpoint for the provider?
      placeholder: |
        https://exampleprovider.com
    validations:
      required: true

  - type: textarea
    attributes:
      label: Provider Description
      description: Briefly describe the provider and what content it offers.
      placeholder: |
        Describe the provider, its benefits, and why it should be added.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation Details
      description: If you have technical knowledge, describe how this provider could be integrated.
      placeholder: |
        API endpoints, authentication, data formats, etc.
        ```
        https://api.exampleprovider.com/watch/{tmdb_id}/
        or 
        https://api.exampleprovider.com/series/{tmdb_id}/season/{season_number}/episode/{episode_number}/
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or examples about the provider request here. **If you have checked the logic of the provider already a little bit and/or found some interesting code/information, please share it here.**
      placeholder: |
        <!-- Optional: Include links, code snippets, or additional information -->
      render: markdown
    validations:
      required: false