name: '[CI] Continuous Integration'

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight UTC

permissions:
    contents: write
    pull-requests: write

jobs:
    chore-dependencies:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: dev
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: |
                  npm install

            - name: Update dependencies
              run: |
                  npx npm-check-updates -u
                  npm install

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: auto/update-deps
                  base: dev
                  title: 'chore: update dependencies'
                  body: |
                      ## 🔄 Automated Dependency Update

                      This PR updates project dependencies to their latest versions.

                      ### Changes
                      - Updated package.json dependencies
                      - Updated package-lock.json lockfile

                      ### Notes
                      - Automated by GitHub Actions
                  commit-message: 'chore: update dependencies to latest versions'
                  author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
                  labels: |
                      chore
                      dependencies
                  assignees: An0n-00
                  draft: false
                  delete-branch: true
                  maintainer-can-modify: true

            - name: Auto-merge PR
              if: success()
              uses: pascalgn/automerge-action@v0.16.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MERGE_METHOD: squash

    chore-prettier:
        runs-on: ubuntu-latest
        needs: chore-dependencies

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: dev
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Prettier
              run: |
                  npm install -g prettier

            - name: Format JSON files using Prettier
              run: |
                  prettier --write . --ignore-path .prettierignore

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: auto/format-prettier
                  base: dev
                  title: 'chore: format files with prettier'
                  body: |
                      ## 🎨 Automated Code Formatting

                      This PR applies Prettier formatting to maintain consistent code style.

                      ### Changes
                      - Applied Prettier formatting rules
                      - Fixed code style inconsistencies

                      ### Notes
                      - Automated by GitHub Actions
                      - No functional changes, style only
                  commit-message: 'chore: apply prettier formatting for consistent code style'
                  author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
                  labels: |
                      chore
                      🎨formatting
                  assignees: An0n-00
                  draft: false
                  delete-branch: true
                  maintainer-can-modify: true

            - name: Auto-merge PR
              if: success()
              uses: pascalgn/automerge-action@v0.16.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MERGE_METHOD: squash
