name: Only allow PRs from Dev to Main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dev to Main
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          HEAD_REPO="${{ github.event.pull_request.head.repo.full_name }}"
          REPO="${{ github.repository }}"

          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"
          echo "Head repo: $HEAD_REPO"
          echo "Repository: $REPO"

          if [[ "$BASE_BRANCH" != "main" || "$HEAD_BRANCH" != "dev" || "$HEAD_REPO" != "$REPO" ]]; then
            echo "::error::Only Pull Requests from 'dev' to 'main' in the same repository are allowed."
            exit 1
          else
            echo "✅ Pull request is valid (Dev → Main)."
          fi
